### ISSUE TITLE
#16 HOME-PAGE contenu pele-mele / Sur une grande résolution, on ne voit pas tout le temps le bouton (+ de nouveautés).

### ISSUE THREAD

**Issue by philippepetitgenet** [plaste/shadok#16]
Ce même bouton arrive par moment en dessous de nouvelles actualité ou tweets chargés.
Aussi, bloquer les colonnes à 5 au maximum sur la largeur. Je n’ai pas répété à tous les coups ce bug

**Comment by plaste** [comment]
Les blocs étant restreint à 5 colonnes, on ne devrait plus avoir le soucis en grande résolution.
