### ISSUE TITLE
#17 HOME-PAGE contenu pele-mele / Freez du contenu pele-mele

### ISSUE THREAD

**Issue by philippepetitgenet** [plaste/shadok#17]
Il faudra effectivement trouver le moyen de « friser » l’affichage des contenus. Je vois absolument la complication que ça peut apporter dans le code de la page en revanche et l'alourdissement au chargement des news en infinite scroll..

**Comment by plaste** [comment]
Le bouton devrait maintenant être toujours visible, on ne dépasse pas 5 colonnes.
